# configuration for [Yarn][]
# https://yarnpkg.com/configuration/yarnrc

---

# default to [caret ranges][Node.js semantic versioning caret ranges] for new dependencies
defaultSemverRangePrefix: ^
# https://yarnpkg.com/configuration/yarnrc#defaultSemverRangePrefix

# Ensure cached dependency archives are committed in to the repository to enable [zero-installs][Yarn zero-installs] and [offline cache][Yarn offline cache]
enableGlobalCache: false
# https://yarnpkg.com/configuration/yarnrc#enableGlobalCache

# Enable [Plug'n'Play][Yarn Plug'n'Play]
nodeLinker: pnp
# https://yarnpkg.com/configuration/yarnrc#nodeLinker

# Enable ECMAScript module loader for [Plug'n'Play][Yarn Plug'n'Play]
pnpEnableEsmLoader: true
# https://yarnpkg.com/configuration/yarnrc#pnpEnableEsmLoader

# Prevent modules from requiring packages not listed as dependencies
pnpMode: strict
# https://yarnpkg.com/configuration/yarnrc#pnpMode


# [Node.js semantic versioning caret ranges]: https://github.com/npm/node-semver#caret-ranges-123-025-004
# [Yarn]: https://yarnpkg.com/
# [Yarn offline cache]: https://yarnpkg.com/features/offline-cache
# [Yarn Plug'n'Play]: https://yarnpkg.com/features/pnp
# [Yarn zero-installs]: https://yarnpkg.com/features/zero-installs
