# configuration for [Yarn][]
# https://yarnpkg.com/configuration/yarnrc

---

# default to [caret ranges][Node.js semantic versioning caret ranges] for new dependencies
defaultSemverRangePrefix: ^
# https://yarnpkg.com/configuration/yarnrc#defaultSemverRangePrefix


# [Node.js semantic versioning caret ranges]: https://github.com/npm/node-semver#caret-ranges-123-025-004
# [Yarn]: https://yarnpkg.com/
